#supposedly this file is ignored when using aws runners...
version: 0.2

phases:
  build:
    commands:
      - make ci
      
artifacts:
  files:
    - 'dist/artifacts/*amd64.iso'
  name: isos/harvester-autoinstall-$(git rev-parse --short HEAD).iso
