name: build
on:
  workflow_dispatch:
  push:
    branches:
    - master
    - v*
  pull_request:
env:
  # Fake up DRONE_BRANCH so it's picked up when dapper gets to
  # scripts/version.  For branches, github.ref_name will be
  # "master" or "v1.x", which is fine, but for PRs it will be
  # something like "697/merge", which doesn't work as a version,
  # so wet just set it to master in this case.
  DRONE_BRANCH: ${{ endsWith(github.ref_name, '/merge') && 'master' || github.ref_name }}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/v') && !startsWith(github.ref, 'refs/tags/v') }}
jobs:
  build-iso:
    name: Build ISO Images
    strategy:
      matrix:
        arch:
        - amd64
    # hdd=50 is somewhat arbitrary here, but seems to give a
    # 77G disk, which is sufficient for ISO builds.
    # The VM runners are named "x64", not "amd64" like other docker things.
    runs-on: codebuild-HarvesterAutoInstaller-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      contents: read
      id-token: write # for reading credential https://github.com/rancher-eio/read-vault-secrets
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build ISO
    - name: Run make ci
      run: make ci

    # Below is essentially duplicated from the main Harvester repo's
    # .github/workflows/build.yml, except we're only publishing branches,
    # not tags.

    - name: Declare branch
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"

    - name: Read Secrets
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/harvester/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/harvester/credentials password | DOCKER_PASSWORD ;
          secret/data/github/repo/${{ github.repository }}/google-auth-key/credentials credential | GOOGLE_AUTH ;

    - name: upload-iso
      uses: 'google-github-actions/upload-cloud-storage@v2'
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      with:
        path: dist/artifacts
        parent: false
        destination: releases.rancher.com/harvester/${{ env.branch }}
        predefinedAcl: publicRead
        headers: |-
          cache-control: public,no-cache,proxy-revalidate
